spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
swagger:
  enabled: true

mybatis-plus:
  type-aliases-package: com.nameless.bbs.entity
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
    banner: false
  configuration:
    cache-enabled:  false
    jdbc-type-for-null: 'null'
    map-underscore-to-camel-case: true
